module.exports = {
	MF_PAYMENT: 'MF_PAYMENT',
	MF_RETURN: 'MF_RETURN',
	MF_WITHDRAWAL: 'MF_WITHDRAWAL',
	MF_POST: 'MF_POST',
	MF_PROFIT: 'MF_PROFIT',
	MF_REPOST: 'MF_REPOST',
	MF_UNFREEZE: 'MF_UNFREEZE',
}
