module.exports = {
	WITHDRAWAL_TYPE_QIWI: 'QIWI',
	WITHDRAWAL_TYPE_PAYEER: 'PAYEER',
	WITHDRAWAL_TYPE_YOOMONEY: 'YOOMONEY',
	WITHDRAWAL_TYPE_MANUAL: 'MANUAL',
	PAYMENT_TYPE_QIWI: 'QIWI',
	PAYMENT_TYPE_YOOMONEY: 'YOOMONEY',
	PAYMENT_TYPE_PAYEER: 'PAYEER'
}
